// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs9gg6KMlAjrGIQwGazclmnojIZB90H3E',
    appId: '1:367625255494:web:48047f9c8b3fc66a792847',
    messagingSenderId: '367625255494',
    projectId: 'flutterfire-ui-codelab-cead0',
    authDomain: 'flutterfire-ui-codelab-cead0.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-cead0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVxZy6yNTHDz6tPD7JLHrSENXCpII6QZ4',
    appId: '1:367625255494:android:d20840c3c15500ed792847',
    messagingSenderId: '367625255494',
    projectId: 'flutterfire-ui-codelab-cead0',
    storageBucket: 'flutterfire-ui-codelab-cead0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHcGVadSyXBNg5knWSDOc9gdZ4QWTgu9c',
    appId: '1:367625255494:ios:077fa250019b07a1792847',
    messagingSenderId: '367625255494',
    projectId: 'flutterfire-ui-codelab-cead0',
    storageBucket: 'flutterfire-ui-codelab-cead0.firebasestorage.app',
    iosBundleId: 'com.example.exercise5a',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHcGVadSyXBNg5knWSDOc9gdZ4QWTgu9c',
    appId: '1:367625255494:ios:077fa250019b07a1792847',
    messagingSenderId: '367625255494',
    projectId: 'flutterfire-ui-codelab-cead0',
    storageBucket: 'flutterfire-ui-codelab-cead0.firebasestorage.app',
    iosBundleId: 'com.example.exercise5a',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs9gg6KMlAjrGIQwGazclmnojIZB90H3E',
    appId: '1:367625255494:web:1c926dfc9cecaaf8792847',
    messagingSenderId: '367625255494',
    projectId: 'flutterfire-ui-codelab-cead0',
    authDomain: 'flutterfire-ui-codelab-cead0.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-cead0.firebasestorage.app',
  );
}
