// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_aYVDXsu7A7EUIQKFeLR7cTPC_P6dqBQ',
    appId: '1:42852781120:android:74ecc8cf9b33fa9732e3a5',
    messagingSenderId: '42852781120',
    projectId: 'info6350-final-garagesaleapp',
    storageBucket: 'info6350-final-garagesaleapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ8rW-yU9VCw2Ouenmylt1L4-rdkvjZqY',
    appId: '1:42852781120:ios:50dd2d8f70c0169a32e3a5',
    messagingSenderId: '42852781120',
    projectId: 'info6350-final-garagesaleapp',
    storageBucket: 'info6350-final-garagesaleapp.firebasestorage.app',
    iosClientId: '42852781120-lheqegj17v2ofuq8lujvahulinijhtg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );
}
